### ISSUE TITLE
add slider

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/python_dhcp_server#3]
you should be able to scroll up and down and know that that is possible

**Comment by joshhazelhurst123** [comment]
I found this python tutorial. I think this is relevant to make the changes to add the slider, just not exactly sure how one would do so. 
I am reading dhcpgui.pyw and I think the changes will needed to be added here. Very useful DHCP python server!

**Comment by niccokunzmann** [comment]
Yes, it is in the dhcp gui, this is the text field:

https://github.com/niccokunzmann/python_dhcp_server/blob/68b3df77ecb09dea3c357032f6645b20b20c7544/server/dhcpgui.pyw#L17

And this seems to be one way of doing it:

https://stackoverflow.com/questions/19646752/python-scrollbar-on-text-widget

You are very welcome to work on it!

**Comment by joshhazelhurst123** [comment]
Great stuff, I had a go at setting up a test environment unsuccessfully with oracle virtual pc. I tried to run a linux distro but I could not access github or drag files across onto the distro. Is there a remote test environment to log into? 

Otherwise, I downloaded [python_dhcp_server_standalone_0.6.zip](https://github.com/niccokunzmann/python_dhcp_server/releases/download/0.6/python_dhcp_server_standalone_0.6.zip)
- From there on windows 11 I forked a release for myself, made changes to dhcpgui.pyw but I have no way to test whether it works or not. Any suggestions on what to do from there? Thanks,

**Comment by niccokunzmann** [comment]
Hi, you can install a client, one of those to clone the repository: https://git-scm.com/download/gui/windows

Then, you can install Python and use e.g. the Python Shell IDLE to edit the files. https://www.python.org/downloads/

**Comment by niccokunzmann** [comment]
Could you send a pull request?

**Comment by joshhazelhurst123** [comment]
Okay, thanks, see here Update dhcpgui.pyw #22
https://github.com/niccokunzmann/python_dhcp_server/pull/22

**Comment by niccokunzmann** [comment]
Thanks @joshhazelhurst123 !
